const PRODUCTS = [
  {
    id: "shoe-001",
    name: "Aero Run X1",
    brand: "NOVO",
    category: "Running Shoes",
    description: "Lightweight performance running shoe with responsive foam and breathable mesh upper. Designed for daily training runs.",
    price: 4299,
    originalPrice: 5999,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop",
    rating: 4.6,
    reviewCount: 128,
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["Black", "White", "Red"],
    stock: 24,
    tags: ["running", "lightweight", "performance", "breathable"],
    url: "product.html?id=shoe-001"
  },
  {
    id: "shoe-002",
    name: "Stride Pro Elite",
    brand: "NOVO",
    category: "Running Shoes",
    description: "Carbon-plated racing shoe built for marathon speed. Ultra-responsive with a propulsive feel.",
    price: 8999,
    originalPrice: 11999,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&h=600&fit=crop",
    rating: 4.8,
    reviewCount: 87,
    sizes: ["7", "8", "9", "10"],
    colors: ["Neon Green", "Black", "White"],
    stock: 12,
    tags: ["running", "marathon", "carbon", "racing"],
    url: "product.html?id=shoe-002"
  },
  {
    id: "shoe-003",
    name: "Trail Walker GTX",
    brand: "NOVO",
    category: "Running Shoes",
    description: "Waterproof trail running shoe with aggressive grip. Built for all-weather adventure on rough terrain.",
    price: 6499,
    originalPrice: 7999,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&h=600&fit=crop",
    rating: 4.4,
    reviewCount: 64,
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["Olive", "Black", "Orange"],
    stock: 31,
    tags: ["trail", "waterproof", "outdoor", "grip"],
    url: "product.html?id=shoe-003"
  },
  {
    id: "sneaker-001",
    name: "Urban Classic",
    brand: "NOVO",
    category: "Sneakers",
    description: "Clean everyday sneaker with premium leather upper. Minimalist design for casual and streetwear.",
    price: 3499,
    originalPrice: 4499,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&h=600&fit=crop",
    rating: 4.3,
    reviewCount: 203,
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["White", "Black", "Navy"],
    stock: 45,
    tags: ["sneakers", "casual", "leather", "streetwear"],
    url: "product.html?id=sneaker-001"
  },
  {
    id: "sneaker-002",
    name: "Retro Wave 90",
    brand: "NOVO",
    category: "Sneakers",
    description: "Throwback chunky sneaker inspired by 90s court shoes. Padded collar and vintage sole unit.",
    price: 5299,
    originalPrice: 6499,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=600&h=600&fit=crop",
    rating: 4.5,
    reviewCount: 156,
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["Cream", "Grey", "Burgundy"],
    stock: 18,
    tags: ["sneakers", "retro", "chunky", "vintage"],
    url: "product.html?id=sneaker-002"
  },
  {
    id: "sneaker-003",
    name: "Cloud Step",
    brand: "NOVO",
    category: "Sneakers",
    description: "Ultra-comfortable sneaker with cloud-soft cushioning. Lightweight knit upper for all-day wear.",
    price: 3999,
    originalPrice: 4999,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&h=600&fit=crop",
    rating: 4.7,
    reviewCount: 291,
    sizes: ["6", "7", "8", "9", "10", "11"],
    colors: ["White", "Grey", "Mint"],
    stock: 52,
    tags: ["sneakers", "comfortable", "knit", "cushioned"],
    url: "product.html?id=sneaker-003"
  },
  {
    id: "jacket-001",
    name: "Wind Shield Pro",
    brand: "NOVO",
    category: "Jackets",
    description: "Windproof and water-resistant running jacket with reflective details. Packs into its own pocket.",
    price: 4999,
    originalPrice: 6999,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=600&fit=crop",
    rating: 4.5,
    reviewCount: 78,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Grey"],
    stock: 15,
    tags: ["jacket", "windproof", "water-resistant", "running"],
    url: "product.html?id=jacket-001"
  },
  {
    id: "jacket-002",
    name: "Thermo Layer",
    brand: "NOVO",
    category: "Jackets",
    description: "Insulated winter running jacket with thermal lining. Reflective accents for low-light visibility.",
    price: 7999,
    originalPrice: 9999,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1544923246-77307dd270d2?w=600&h=600&fit=crop",
    rating: 4.6,
    reviewCount: 45,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Dark Green"],
    stock: 9,
    tags: ["jacket", "winter", "insulated", "thermal"],
    url: "product.html?id=jacket-002"
  },
  {
    id: "jacket-003",
    name: "Breeze Mesh Vest",
    brand: "NOVO",
    category: "Jackets",
    description: "Breathable mesh running vest for warm-weather layering. Minimal weight with maximum airflow.",
    price: 2499,
    originalPrice: 3499,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1546832250-7c0e33be636e?w=600&h=600&fit=crop",
    rating: 4.2,
    reviewCount: 33,
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Black", "Neon Yellow"],
    stock: 27,
    tags: ["jacket", "vest", "breathable", "mesh"],
    url: "product.html?id=jacket-003"
  },
  {
    id: "watch-001",
    name: "Chrono Sport",
    brand: "NOVO",
    category: "Watches",
    description: "GPS running watch with heart rate monitor, VO2 max estimation, and 7-day battery life.",
    price: 12999,
    originalPrice: 15999,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop",
    rating: 4.7,
    reviewCount: 112,
    sizes: ["One Size"],
    colors: ["Black", "White", "Blue"],
    stock: 21,
    tags: ["watch", "gps", "running", "heart-rate"],
    url: "product.html?id=watch-001"
  },
  {
    id: "watch-002",
    name: "Daily Minimal",
    brand: "NOVO",
    category: "Watches",
    description: "Sleek everyday watch with Japanese quartz movement. Sapphire crystal and genuine leather strap.",
    price: 6999,
    originalPrice: 8999,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=600&h=600&fit=crop",
    rating: 4.4,
    reviewCount: 89,
    sizes: ["One Size"],
    colors: ["Silver", "Gold", "Rose Gold"],
    stock: 16,
    tags: ["watch", "casual", "leather", "minimal"],
    url: "product.html?id=watch-002"
  },
  {
    id: "bag-001",
    name: "Trail Pack 28L",
    brand: "NOVO",
    category: "Backpacks",
    description: "Technical trail running backpack with hydration sleeve and adjustable sternum strap. 28-liter capacity.",
    price: 5499,
    originalPrice: 6999,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&h=600&fit=crop",
    rating: 4.5,
    reviewCount: 67,
    sizes: ["One Size"],
    colors: ["Black", "Olive", "Grey"],
    stock: 19,
    tags: ["backpack", "trail", "hydration", "outdoor"],
    url: "product.html?id=bag-001"
  },
  {
    id: "bag-002",
    name: "City Commuter",
    brand: "NOVO",
    category: "Backpacks",
    description: "Water-resistant commuter backpack with padded laptop sleeve. Clean design for work and gym.",
    price: 3999,
    originalPrice: 5499,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1622260614153-03223fb72052?w=600&h=600&fit=crop",
    rating: 4.3,
    reviewCount: 142,
    sizes: ["One Size"],
    colors: ["Black", "Navy", "Grey"],
    stock: 34,
    tags: ["backpack", "commuter", "laptop", "water-resistant"],
    url: "product.html?id=bag-002"
  },
  {
    id: "acc-001",
    name: "Performance Sunglasses",
    brand: "NOVO",
    category: "Accessories",
    description: "Polarized sports sunglasses with anti-fog coating and adjustable nose pads. UV400 protection.",
    price: 2299,
    originalPrice: 3499,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=600&fit=crop",
    rating: 4.4,
    reviewCount: 178,
    sizes: ["One Size"],
    colors: ["Black/Red", "White/Blue", "Clear"],
    stock: 41,
    tags: ["sunglasses", "polarized", "sports", "uv-protection"],
    url: "product.html?id=acc-001"
  },
  {
    id: "acc-002",
    name: "Swift Running Socks 3-Pack",
    brand: "NOVO",
    category: "Accessories",
    description: "Moisture-wicking performance running socks with arch support and seamless toe. Pack of 3.",
    price: 799,
    originalPrice: 1199,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1586350977771-b3b0abd50c87?w=600&h=600&fit=crop",
    rating: 4.6,
    reviewCount: 312,
    sizes: ["S", "M", "L"],
    colors: ["White", "Black", "Grey"],
    stock: 68,
    tags: ["socks", "running", "moisture-wicking", "performance"],
    url: "product.html?id=acc-002"
  },
  {
    id: "acc-003",
    name: "Flex Running Belt",
    brand: "NOVO",
    category: "Accessories",
    description: "Minimalist running belt with secure phone pocket. Adjustable fit, bounce-free design.",
    price: 1299,
    originalPrice: 1799,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=600&h=600&fit=crop",
    rating: 4.2,
    reviewCount: 96,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Grey", "Pink"],
    stock: 53,
    tags: ["belt", "running", "phone", "storage"],
    url: "product.html?id=acc-003"
  },
  {
    id: "acc-004",
    name: "Hydro Flask 750ml",
    brand: "NOVO",
    category: "Accessories",
    description: "Double-wall insulated stainless steel bottle. Keeps drinks cold for 24h or hot for 12h.",
    price: 1499,
    originalPrice: 1999,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&h=600&fit=crop",
    rating: 4.5,
    reviewCount: 234,
    sizes: ["750ml"],
    colors: ["Black", "White", "Forest Green"],
    stock: 42,
    tags: ["bottle", "insulated", "stainless-steel", "hydration"],
    url: "product.html?id=acc-004"
  },
  {
    id: "shoe-004",
    name: "Recovery Slide",
    brand: "NOVO",
    category: "Running Shoes",
    description: "Post-run recovery slide with contoured footbed and soft EVA foam. Relieves tired feet after training.",
    price: 1999,
    originalPrice: 2999,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1603808033192-082d6919d3e1?w=600&h=600&fit=crop",
    rating: 4.1,
    reviewCount: 54,
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["Black", "White", "Grey"],
    stock: 38,
    tags: ["recovery", "slide", "comfort", "eva"],
    url: "product.html?id=shoe-004"
  },
  {
    id: "sneaker-004",
    name: "Platform Edge",
    brand: "NOVO",
    category: "Sneakers",
    description: "Chunky platform sneaker with exaggerated sole unit. Statement piece for streetwear looks.",
    price: 5999,
    originalPrice: 7499,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1605348532760-6753d2c43329?w=600&h=600&fit=crop",
    rating: 4.3,
    reviewCount: 71,
    sizes: ["6", "7", "8", "9", "10"],
    colors: ["White", "Black", "Tan"],
    stock: 22,
    tags: ["sneakers", "platform", "chunky", "streetwear"],
    url: "product.html?id=sneaker-004"
  },
  {
    id: "jacket-004",
    name: "Packable Rain Shell",
    brand: "NOVO",
    category: "Jackets",
    description: "Ultralight packable rain jacket. Fully seam-sealed with adjustable hood. Packs into inner pocket.",
    price: 3499,
    originalPrice: 4999,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&h=600&fit=crop",
    rating: 4.4,
    reviewCount: 58,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Blue", "Yellow"],
    stock: 26,
    tags: ["jacket", "rain", "packable", "lightweight"],
    url: "product.html?id=jacket-004"
  },
  {
    id: "watch-003",
    name: "Endurance GPS",
    brand: "NOVO",
    category: "Watches",
    description: "Multi-sport GPS watch with barometric altimeter, compass, and 14-day battery. Built for ultrarunners.",
    price: 18999,
    originalPrice: 22999,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&h=600&fit=crop",
    rating: 4.8,
    reviewCount: 43,
    sizes: ["One Size"],
    colors: ["Black", "Camo"],
    stock: 8,
    tags: ["watch", "gps", "ultrarunning", "endurance"],
    url: "product.html?id=watch-003"
  },
  {
    id: "bag-003",
    name: "Gym Duffle 40L",
    brand: "NOVO",
    category: "Backpacks",
    description: "Spacious gym duffle with ventilated shoe compartment and wet pocket. Removable shoulder strap.",
    price: 2999,
    originalPrice: 3999,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1581605405669-fcdf81165afa?w=600&h=600&fit=crop",
    rating: 4.2,
    reviewCount: 88,
    sizes: ["One Size"],
    colors: ["Black", "Grey", "Navy"],
    stock: 31,
    tags: ["duffle", "gym", "ventilated", "shoe-pocket"],
    url: "product.html?id=bag-003"
  },
  {
    id: "acc-005",
    name: "Wrist Sweatband 2-Pack",
    brand: "NOVO",
    category: "Accessories",
    description: "Absorbent terry cotton wrist sweatbands with embroidered logo. Pack of 2.",
    price: 499,
    originalPrice: 699,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&h=600&fit=crop",
    rating: 4.0,
    reviewCount: 145,
    sizes: ["One Size"],
    colors: ["White", "Black", "Red"],
    stock: 73,
    tags: ["sweatband", "cotton", "terry", "workout"],
    url: "product.html?id=acc-005"
  },
  {
    id: "acc-006",
    name: "Foam Roller 45cm",
    brand: "NOVO",
    category: "Accessories",
    description: "High-density EVA foam roller for muscle recovery and myofascial release. Textured surface for deeper massage.",
    price: 1199,
    originalPrice: 1599,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&h=600&fit=crop",
    rating: 4.5,
    reviewCount: 198,
    sizes: ["45cm"],
    colors: ["Black", "Blue", "Purple"],
    stock: 44,
    tags: ["foam-roller", "recovery", "massage", "eva"],
    url: "product.html?id=acc-006"
  }
];
